### ISSUE TITLE
In the 1.19 version of the mod, certain items crash the game.

### ISSUE THREAD

**Issue by SlayerTheChikken** [DanikingRD/BackTools#15]
This is from holding an engineering press from AE2, it happens with other mods too though.

```
net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: ae2:MaterialItem[engineering_processor_press]
	at net.minecraft.class_2960.<init>(class_2960.java:41)
	at net.minecraft.class_2960.<init>(class_2960.java:50)
	at com.daniking.backtools.ConfigHandler.isItemEnabled(ConfigHandler.java:35)
	at com.daniking.backtools.HeldItemContext.tick(HeldItemContext.java:45)
	at net.minecraft.class_1657.handler$bjh00b$backtools$tick(com/daniking/backtools/mixin/PlayerEntityTickMixin.java [backtools.mixins.json]:24)
	at net.minecraft.class_1657.method_5773(class_1657.java)
	at net.minecraft.class_746.method_5773(class_746.java:229)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1851)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2960.<init>(class_2960.java:41)
	at net.minecraft.class_2960.<init>(class_2960.java:50)
	at com.daniking.backtools.ConfigHandler.isItemEnabled(ConfigHandler.java:35)
	at com.daniking.backtools.HeldItemContext.tick(HeldItemContext.java:45)
	at net.minecraft.class_1657.handler$bjh00b$backtools$tick(com/daniking/backtools/mixin/PlayerEntityTickMixin.java [backtools.mixins.json]:24)
	at net.minecraft.class_1657.method_5773(class_1657.java)
	at net.minecraft.class_746.method_5773(class_746.java:229)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
```

**Comment by FireInstall** [comment]
Ported a fix back, just in case updating to 1.20 is not feasable for you.
[unoffical ](https://github.com/FireInstall/BackTools/releases/tag/1.19.4-3)
