### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [DanikingRD/BackTools#2]
java.lang.NoSuchFieldError: field_11142
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at com.daniking.backtools.ConfigHandler.isItemEnabled(ConfigHandler.java:35)
	at com.daniking.backtools.HeldItemContext.tick(HeldItemContext.java:45)
	at net.minecraft.entity.player.PlayerEntity.handler$zec001$tick(PlayerEntity:5350)
	at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity)
	at net.minecraft.client.network.AbstractClientPlayerEntity.tick(AbstractClientPlayerEntity:1636)
	at net.minecraft.client.network.ClientPlayerEntity.tick(ClientPlayerEntity:218)
	at net.minecraft.client.world.ClientWorld.tickEntity(ClientWorld:269)
	at net.minecraft.world.World.tickEntity(World:482)
	at net.minecraft.client.world.ClientWorld.method_32124(ClientWorld:252)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld:248)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1885)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1150)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:781)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ldanidev** [comment]
Closing this issue since 1.19 is no longer supported. You can play at the latest 1.20.1 version.
