### ISSUE TITLE
Weird config crash even with default config

### ISSUE THREAD

**Issue by Partonetrain** [DanikingRD/BackTools#20]
Not sure what is going on here, just started a new world. Can't reproduce with BackTools alone - will investigate further.
```
net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:net.minecraft.class_1739{minecraft:air}
	at net.minecraft.class_2960.method_45137(class_2960.java:252)
	at net.minecraft.class_2960.<init>(class_2960.java:47)
	at com.daniking.backtools.ConfigHandler.isItemEnabled(ConfigHandler.java:39)
	at com.daniking.backtools.HeldItemContext.tick(HeldItemContext.java:44)
	at net.minecraft.class_1657.handler$znn001$backtools$tick(class_1657.java:7387)
	at net.minecraft.class_1657.method_5773(class_1657.java)
	at net.minecraft.class_742.method_5773(class_742.java:73)
	at net.minecraft.class_746.method_5773(class_746.java:219)
	at net.minecraft.class_638.method_18646(class_638.java:272)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_638.method_32124(class_638.java:255)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:251)
	at net.minecraft.class_310.method_1574(class_310.java:1901)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by FireInstall** [comment]
I have a pretty good Idea of the problem.
What version of the mod are you using?

**Comment by Partonetrain** [comment]
backtools-1.20.1-2

**Comment by FireInstall** [comment]
I (probably) fixed this in the latest release.
But it runs only on 1.20.3/4.

Could you please test this again in the [latest version](https://modrinth.com/mod/backtools/version/1.20.4-0)?

**Comment by Partonetrain** [comment]
That version works fine, but I can't test it in the instance it's crashing in (again, backtools-1.20.1-2 works fine on its own). My best guess is that some mod is mixing in to one of the Minecraft classes listed in the crashlog in an incompatible way?

**Comment by FireInstall** [comment]
Ok, I ported the fix back just for you: [unofficial 1.20.1](https://github.com/FireInstall/BackTools/releases/tag/1.20.1-3)

**Comment by Partonetrain** [comment]
I was actually going to try backporting that myself this weekend. That worked, thank you for the backport!

**Comment by Partonetrain** [comment]
The game launched, but I got the same crash with a different item once I got into the game

**Comment by FireInstall** [comment]
Are you shure this is the same crash and does nothing say about belts?
In this case I will have a deeper look into the problem.

**Comment by FireInstall** [comment]
OK, I got another one.
Could you please test if this one works? [unofficial 1.20.1](https://github.com/FireInstall/BackTools/releases/tag/1.20.1-4)
If this doesn't work, then we have to filter out AirBlockItems specifically.



@DanikingRD May I ask: What was the reason for creating a new Identifer in `isItemEnabled`, line 39 in `com.daniking.backtools.ConfigHandler` instead of just using `Registries.ITEM.getId(item)`?
Seems like you were trying to solve a problem here, but I can't figure out what that was.

**Comment by Partonetrain** [comment]
It was, in fact, not the same crash. Thank you for catching that.
1.20.1-4 seems to work fine with the default config.

**Comment by FireInstall** [comment]
Nice! Thanks for testing!
Depending on DanikingRD's answer, I will open an PR to get this fix into the official versions!

**Comment by ldanidev** [comment]
> OK, I got another one. Could you please test if this one works? [unofficial 1.20.1](https://github.com/FireInstall/BackTools/releases/tag/1.20.1-4) If this doesn't work, then we have to filter out AirBlockItems specifically.
> 
> @DanikingRD May I ask: What was the reason for creating a new Identifer in `isItemEnabled`, line 39 in `com.daniking.backtools.ConfigHandler` instead of just using `Registries.ITEM.getId(item)`? Seems like you were trying to solve a problem here, but I can't figure out what that was.

Tbh i don't remember if it was supposed to fix something. I wanted to refactor some of the code but it never happened. If you can find a better way of handling the config load feel free to submit that.

**Comment by FireInstall** [comment]
Alright then, there is the PR
